// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVcWsLJokXpQsHzyTwv3G25OuuPkIIN38',
    appId: '1:664498886284:web:bd9aed2496bdeb9159cda9',
    messagingSenderId: '664498886284',
    projectId: 'raou-claude',
    authDomain: 'raou-claude.firebaseapp.com',
    storageBucket: 'raou-claude.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL3B9SimAP5guT3XL3kPInkk4xQtC60gQ',
    appId: '1:664498886284:android:43fc9601103afbb659cda9',
    messagingSenderId: '664498886284',
    projectId: 'raou-claude',
    storageBucket: 'raou-claude.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVHW-hXZvKG23gZl9yNuDEq8Hkm8sSI1I',
    appId: '1:664498886284:ios:bd9aed2496bdeb9159cda9',
    messagingSenderId: '664498886284',
    projectId: 'raou-claude',
    storageBucket: 'raou-claude.firebasestorage.app',
    iosBundleId: 'com.raou.claude.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVHW-hXZvKG23gZl9yNuDEq8Hkm8sSI1I',
    appId: '1:664498886284:ios:bd9aed2496bdeb9159cda9',
    messagingSenderId: '664498886284',
    projectId: 'raou-claude',
    storageBucket: 'raou-claude.firebasestorage.app',
    iosBundleId: 'com.raou.claude.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVcWsLJokXpQsHzyTwv3G25OuuPkIIN38',
    appId: '1:664498886284:web:bd9aed2496bdeb9159cda9',
    messagingSenderId: '664498886284',
    projectId: 'raou-claude',
    authDomain: 'raou-claude.firebaseapp.com',
    storageBucket: 'raou-claude.firebasestorage.app',
  );
}